"""Python code generator for AgentMap graphs."""
from typing import Dict, List
from agentmap.services.agent.agent_registry_service import AgentRegistryService
from agentmap.services.function_resolution_service import FunctionResolutionService

IMPORT_HEADER = """from langgraph.graph import StateGraph
from agentmap.agents.builtins.openai_agent import OpenAIAgent
from agentmap.agents.builtins.anthropic_agent import AnthropicAgent
from agentmap.agents.builtins.google_agent import GoogleAgent
from agentmap.agents.builtins.echo_agent import EchoAgent
from agentmap.agents.builtins.default_agent import DefaultAgent
from agentmap.agents.builtins.branching_agent import BranchingAgent
from agentmap.agents.builtins.success_agent import SuccessAgent
from agentmap.agents.builtins.failure_agent import FailureAgent
"""

class PythonCodeGenerator:
    """Generator for Python code representation of graphs."""
    def __init__(self, function_resolution_service: FunctionResolutionService, agent_registry_service: AgentRegistryService):
        self.function_resolution = function_resolution_service
        self.agent_registry = agent_registry_service

    def generate(self, graph_name: str, graph_def: Dict, state_schema: str) -> List[str]:
        lines = [IMPORT_HEADER]
        if state_schema.startswith("pydantic:"):
            model_name = state_schema.split(":", 1)[1]
            lines.append(f"from agentmap.schemas.{model_name.lower()} import {model_name}")
        for node in graph_def.values():
            for target in node.edges.values():
                func = self.function_resolution.extract_func_ref(target)
                if func:
                    lines.append(f"from agentmap.functions.{func} import {func}")
        schema_arg = state_schema if state_schema != "dict" else "dict"
        lines.extend(["", f"# Graph: {graph_name}", f"builder = StateGraph({schema_arg})"])
        for node in graph_def.values():
            agent_class_obj = self.agent_registry.get_agent_class(node.agent_type)
            agent_class = agent_class_obj.__name__ if agent_class_obj else "DefaultAgent"
            context = f'{{"input_fields": {node.inputs}, "output_field": "{node.output}"}}'
            prompt_text = node.prompt or ""
            lines.append(f'builder.add_node("{node.name}", {agent_class}(name="{node.name}", prompt="{prompt_text}", context={context}))')
        entry = next(iter(graph_def))
        lines.extend([f'builder.set_entry_point("{entry}")', "graph = builder.compile()"])
        return lines

def generate_source_code(graph_def: Dict, state_schema: str, agent_registry_service: AgentRegistryService) -> List[str]:
    lines = [f"builder = StateGraph({state_schema})"] if state_schema != "dict" else ["builder = StateGraph(dict)"]
    for node in graph_def.values():
        agent_class_obj = agent_registry_service.get_agent_class(node.agent_type)
        agent_class = agent_class_obj.__name__ if agent_class_obj else "DefaultAgent"
        lines.append(f'builder.add_node("{node.name}", {agent_class}())')
    entry = next(iter(graph_def))
    lines.extend([f'builder.set_entry_point("{entry}")', "graph = builder.compile()"])
    return lines

def generate_debug_code(graph_name: str, graph_def: Dict, state_schema: str, python_generator: PythonCodeGenerator) -> List[str]:
    lines = [f"# Debug Export for Graph: {graph_name}", f"# State Schema: {state_schema}", "# Generated by GraphOutputService", "", "# === GRAPH STRUCTURE ==="]
    for node_name, node in graph_def.items():
        prompt_display = (node.prompt[:100] + "...") if len(node.prompt or "") > 100 else (node.prompt or "")
        lines.extend(["", f"# Node: {node_name}", f"#   Agent Type: {node.agent_type}", f"#   Inputs: {node.inputs}", f"#   Output: {node.output}", f"#   Prompt: {prompt_display}", f"#   Edges: {node.edges}"])
    lines.extend(["", "# === EXECUTABLE CODE ===", ""])
    lines.extend(python_generator.generate(graph_name, graph_def, state_schema))
    return lines
